### ISSUE TITLE
Exercices

### ISSUE THREAD

**Issue by Vayel** [Vayel/article-async#2]
Ajouter des exercices à https://github.com/ArnaudCalmettes/article-async/issues/4 et https://github.com/ArnaudCalmettes/article-async/issues/11 : on exécuterait des coroutines contenant des `print` et demanderait au lecteur de deviner l'ordre d'apparition des messages dans la console.

**Comment by ArnaudCalmettes** [comment]
Non. C'est un article. Pas un tuto.
